name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.8.3
  get_it: ^8.0.3
  flutter_riverpod: ^2.6.1
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.17
  intl: ^0.20.2
  equatable: ^2.0.7
  shared_preferences: ^2.5.5
  flutter_secure_storage: ^9.2.4
  video_player: ^2.9.2
  pdfrx: 2.4.7
  http: ^1.6.0
  qr_flutter: ^4.1.0
  mobile_scanner: ^7.4.0
  file_selector: ^1.1.0
  archive: ^4.0.9
  xml: ^7.0.1
  device_info_plus: ^12.4.0
  geolocator: ^14.0.2
  firebase_core: ^4.13.0
  firebase_messaging: ^16.5.0
  flutter_local_notifications: ^22.3.0
  url_launcher: ^6.3.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.6
  csv: ^8.0.0
  share_plus: ^12.0.2
  pdf: ^3.13.0
  printing: ^5.15.0
  timeago: ^3.7.1
  provider: ^6.1.5+1
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  mocktail: ^1.0.4

flutter:
  uses-material-design: true
