import 'package:flutter/widgets.dart';

class AppLocalizations {
  final Locale locale;

  const AppLocalizations(this.locale);

  static const supportedLocales = [Locale('en'), Locale('ar')];

  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations) ??
        const AppLocalizations(Locale('en'));
  }

  static const LocalizationsDelegate<AppLocalizations> delegate =
      _AppLocalizationsDelegate();

  bool get isArabic => locale.languageCode == 'ar';

  String t(String key) {
    final language = isArabic ? _ar : _en;
    return language[key] ?? _en[key] ?? key;
  }

  static const Map<String, String> _en = {
    'settings': 'Settings',
    'language': 'Language',
    'english': 'English',
    'arabic': 'Arabic',
    'app_settings': 'App settings',
    'display_language': 'Display language',
    'display_language_subtitle': 'Choose the language used across the app.',
    'notifications': 'Notifications',
    'push_notifications': 'Push notifications',
    'push_notifications_subtitle':
        'Receive real-time alerts from Firebase Cloud Messaging.',
    'enabled': 'Enabled',
    'disabled': 'Disabled',
    'close': 'Close',
    'save': 'Save',
    'retry': 'Retry',
    'refresh': 'Refresh',
    'sign_out': 'Sign out',
    'Opening student portal': 'Opening student portal',
    'Checking your session, preferences, and secure access.':
        'Checking your session, preferences, and secure access.',
    'Opening teacher portal': 'Opening teacher portal',
    'Preparing classes, workspace, and secure access.':
        'Preparing classes, workspace, and secure access.',
    'Opening guardian portal': 'Opening guardian portal',
    'Loading linked children, alerts, and secure access.':
        'Loading linked children, alerts, and secure access.',
    'Opening admin dashboard': 'Opening admin dashboard',
    'Loading management tools, permissions, and secure access.':
        'Loading management tools, permissions, and secure access.',
    'Opening staff portal': 'Opening staff portal',
    'Loading operations, permissions, and secure access.':
        'Loading operations, permissions, and secure access.',
    'Secure unlock': 'Secure unlock',
    'Checking your fingerprint and preparing the academy portal.':
        'Checking your fingerprint and preparing the academy portal.',
    'Preparing lesson workspace...': 'Preparing lesson workspace...',
    'Loading your notes and saved board...':
        'Loading your notes and saved board...',
    'Downloading lesson PDF...': 'Downloading lesson PDF...',
    'Syncing teacher board and your workspace...':
        'Syncing teacher board and your workspace...',
    'Run': 'Run',
    'Terminal Output': 'Terminal Output',
    'Starter code': 'Starter code',
    'Format': 'Format',
    'Preparing sandbox': 'Preparing sandbox',
    'Compiling': 'Compiling',
    'Finished': 'Finished',
    'Stopped': 'Stopped',
    'The PDF could not be downloaded. Please check the file link and try again.':
        'The PDF could not be downloaded. Please check the file link and try again.',
    'The PDF download took too long. Please check your connection and try again.':
        'The PDF download took too long. Please check your connection and try again.',
    'The PDF could not be opened. Please check your connection and try again.':
        'The PDF could not be opened. Please check your connection and try again.',
    'startup_failed': 'Startup failed',
    'academy_platform': 'Academy Platform',
    'admin_dashboard': 'Academy - Admin Dashboard',
    'student_portal': 'Academy - Student Portal',
    'teacher_portal': 'Academy - Teacher Portal',
    'parent_portal': 'Academy - Parent Portal',
    'staff_portal': 'Academy - Staff Portal',
    'Overview': 'Overview',
    'Home': 'Home',
    'Classes': 'Classes',
    'Workspace': 'Workspace',
    'Analytics': 'Analytics',
    'Branches': 'Branches',
    'Subjects': 'Subjects',
    'Groups': 'Groups',
    'Schedules': 'Schedules',
    'Students': 'Students',
    'Parents': 'Parents',
    'Teachers': 'Teachers',
    'Staff': 'Staff',
    'Curriculum': 'Curriculum',
    'Questions': 'Questions',
    'Homework': 'Homework',
    'Exams': 'Exams',
    'Attendance': 'Attendance',
    'Finance': 'Finance',
    'Security': 'Security',
    'Audit': 'Audit',
    'Replay': 'Replay',
    'Import': 'Import',
    'Settings': 'Settings',
    'Lessons': 'Lessons',
    'Assessments': 'Assessments',
    'Boards': 'Boards',
    'Announcements': 'Announcements',
    'Billing': 'Billing',
    'Account': 'Account',
    'Progress': 'Progress',
    'Payments': 'Payments',
    'Report': 'Report',
    'Teaching': 'Teaching',
    'Academic': 'Academic',
    'Operations': 'Operations',
    'Queues': 'Queues',
    'Notifications': 'Notifications',
    'Reports': 'Reports',
    'Academy Suite': 'Academy Suite',
    'Admin operations': 'Admin operations',
    'Student portal': 'Student portal',
    'Teacher Studio': 'Teacher Studio',
    'Teaching workspace': 'Teaching workspace',
    'Operations workspace': 'Operations workspace',
    'Admin': 'Admin',
    'Clear search': 'Clear search',
    'Search': 'Search',
    'Create': 'Create',
    'Edit': 'Edit',
    'Delete': 'Delete',
    'Actions': 'Actions',
    'Add Exam': 'Add Exam',
    'Add Homework': 'Add Homework',
    'Add Question': 'Add Question',
    'Are you sure you want to delete this exam?':
        'Are you sure you want to delete this exam?',
    'Are you sure you want to delete this homework?':
        'Are you sure you want to delete this homework?',
    'Are you sure you want to delete this question?':
        'Are you sure you want to delete this question?',
    'Create Homework Assignment': 'Create Homework Assignment',
    'Create New Exam': 'Create New Exam',
    'Create Question': 'Create Question',
    'Create an active group first.': 'Create an active group first.',
    'Create reusable assessment questions by subject.':
        'Create reusable assessment questions by subject.',
    'Delete Exam': 'Delete Exam',
    'Delete Homework': 'Delete Homework',
    'Delete Question': 'Delete Question',
    'Duration (Minutes)': 'Duration (Minutes)',
    'Edit Exam': 'Edit Exam',
    'Edit Homework': 'Edit Homework',
    'Edit Homework Assignment': 'Edit Homework Assignment',
    'Edit Question': 'Edit Question',
    'Exam & Quiz Management': 'Exam & Quiz Management',
    'Exam Title': 'Exam Title',
    'Exam published successfully!': 'Exam published successfully!',
    'Exam report generated.': 'Exam report generated.',
    'Exam updated successfully!': 'Exam updated successfully!',
    'Failed to close': 'Failed to close',
    'Failed to delete': 'Failed to delete',
    'Failed to generate report': 'Failed to generate report',
    'Homework Management': 'Homework Management',
    'Homework Title': 'Homework Title',
    'Homework assignment published!': 'Homework assignment published!',
    'Homework updated successfully!': 'Homework updated successfully!',
    'Instructions / Description': 'Instructions / Description',
    'Max Score / Points': 'Max Score / Points',
    'Multiple Choice (MCQ)': 'Multiple Choice (MCQ)',
    'No active subject found.': 'No active subject found.',
    'No exam data': 'No exam data',
    'No exams found.': 'No exams found.',
    'No homework assignments found.': 'No homework assignments found.',
    'No homework data': 'No homework data',
    'No question data': 'No question data',
    'No questions found in question bank.':
        'No questions found in question bank.',
    'Passing Score': 'Passing Score',
    'Publish Exam': 'Publish Exam',
    'Publish Homework': 'Publish Homework',
    'Publish group assignments with due dates and scoring.':
        'Publish group assignments with due dates and scoring.',
    'Publish group exams with explicit duration and scoring.':
        'Publish group exams with explicit duration and scoring.',
    'Question Bank': 'Question Bank',
    'Question Prompt / Text': 'Question Prompt / Text',
    'Question Type': 'Question Type',
    'Question created!': 'Question created!',
    'Question updated!': 'Question updated!',
    'Select due date': 'Select due date',
    'Short Answer': 'Short Answer',
    'True / False': 'True / False',
    'Update failed': 'Update failed',
    'View Submissions': 'View Submissions',
    'View': 'View',
    'Export': 'Export',
    'Upload': 'Upload',
    'Download': 'Download',
    'Request': 'Request',
    'Submit': 'Submit',
    'Cancel': 'Cancel',
    'Send': 'Send',
    'Acknowledge': 'Acknowledge',
    'Mark read': 'Mark read',
    'Save Profile': 'Save Profile',
    'Update Password': 'Update Password',
    'No lessons available': 'No lessons available',
    'Lessons appear here after your teacher publishes them.':
        'Lessons appear here after your teacher publishes them.',
    'No assessments available': 'No assessments available',
    'Published homework and exams will appear here.':
        'Published homework and exams will appear here.',
    'No attendance records': 'No attendance records',
    'Attendance appears after sessions are marked.':
        'Attendance appears after sessions are marked.',
    'No published boards': 'No published boards',
    'No announcements': 'No announcements',
    'Targeted announcements will appear here.':
        'Targeted announcements will appear here.',
    'No notifications': 'No notifications',
    'Academic and payment alerts will appear here.':
        'Academic and payment alerts will appear here.',
    'No billing records': 'No billing records',
    'Invoices appear here when a subscription is assigned.':
        'Invoices appear here when a subscription is assigned.',
    'No operations data': 'No operations data',
    'Refresh after staff permissions are assigned.':
        'Refresh after staff permissions are assigned.',
    'No linked children': 'No linked children',
    'Ask the academy admin to link your account to a student profile.':
        'Ask the academy admin to link your account to a student profile.',
    'Teacher Portal': 'Teacher Portal',
    'My Teaching Workspaces': 'My Teaching Workspaces',
    'Academic & Content Workspace': 'Academic & Content Workspace',
    'Operations & Grading Workspace': 'Operations & Grading Workspace',
    'Class Details': 'Class details',
    'Student Roster': 'Student roster',
    'No replay sessions': 'No replay sessions',
    'Replay data appears after students open lessons.':
        'Replay data appears after students open lessons.',
    'Select a replay session.': 'Select a replay session.',
    'No events were recorded.': 'No events were recorded.',
    'Pause replay': 'Pause replay',
    'Play replay': 'Play replay',
    'Now': 'Now',
    'pages': 'pages',
    'Failed to create session': 'Failed to create session',
    'Request Leave': 'Request Leave',
    'Session': 'Session',
    'Reason': 'Reason',
    'Answer / notes': 'Answer / notes',
    'Attachment URL': 'Attachment URL',
    'Full name': 'Full name',
    'Phone number': 'Phone number',
    'Avatar image URL': 'Avatar image URL',
    'New password': 'New password',
    'Reviewer note': 'Reviewer note',
    'Notes': 'Notes',
    'Resolution note': 'Resolution note',
    'Class session': 'Class session',
    'Child': 'Child',
    'Got it': 'Got it',
    'active': 'active',
    'paid': 'paid',
    'published': 'published',
    'pending': 'pending',
    'archived': 'archived',
    'suspended': 'suspended',
    'issued': 'issued',
    'overdue': 'overdue',
    'partially_paid': 'partially paid',
    'present': 'present',
    'absent': 'absent',
    'late': 'late',
    'excused': 'excused',
    'approved': 'approved',
    'rejected': 'rejected',
    'submitted': 'submitted',
    'graded': 'graded',
    'failed': 'failed',
    'unknown': 'unknown',
    'PDF': 'PDF',
    'Lesson': 'Lesson',
    'Group': 'Group',
    'Student': 'Student',
    'Staff Member': 'Staff Member',
    'Operations Portal': 'Operations Portal',
    'Students, groups, attendance, leave, and payments':
        'Students, groups, attendance, leave, and payments',
    'Guardian Portal': 'Guardian Portal',
    'Parent overview': 'Parent overview',
    'linked children': 'linked children',
    'active groups': 'active groups',
    'General request': 'General request',
    'General leave request': 'General leave request',
    'Leave request': 'Leave request',
    'No date': 'No date',
    'Leave request sent.': 'Leave request sent.',
    'Homework submitted.': 'Homework submitted.',
    'Your learning workspace opens only from published lessons assigned to your active groups.':
        'Your learning workspace opens only from published lessons assigned to your active groups.',
    'No lesson ready': 'No lesson ready',
    'Resume lesson': 'Resume lesson',
    'No published lesson is available.': 'No published lesson is available.',
    'Enroll the student and publish curriculum content to start.':
        'Enroll the student and publish curriculum content to start.',
    'You are enrolled, but no published lessons are available yet.':
        'You are enrolled, but no published lessons are available yet.',
    'You are not enrolled in any active group yet.':
        'You are not enrolled in any active group yet.',
    'Lesson progress': 'Lesson progress',
    'Attendance rate': 'Attendance rate',
    'Balance due': 'Balance due',
    'Unread alerts': 'Unread alerts',
    'Active groups': 'Active groups',
    'Groups currently assigned to the selected child.':
        'Groups currently assigned to the selected child.',
    'No active groups for this child.': 'No active groups for this child.',
    'Next learning item': 'Next learning item',
    'Published lessons': 'Published lessons',
    'Progress is calculated from the student reading history.':
        'Progress is calculated from the student reading history.',
    'No published lessons available for this child yet.':
        'No published lessons available for this child yet.',
    'Present': 'Present',
    'Absent': 'Absent',
    'Late': 'Late',
    'Leave requests': 'Leave requests',
    'Submit and track absence excuses.': 'Submit and track absence excuses.',
    'Invoices': 'Invoices',
    'No invoices issued for this child.': 'No invoices issued for this child.',
    'Receipts': 'Receipts',
    'Receipt': 'Receipt',
    'Electronic Receipt': 'Electronic Receipt',
    'No payment receipts generated yet.': 'No payment receipts generated yet.',
    'Amount Paid': 'Amount Paid',
    'Issued': 'Issued',
    'Reference': 'Reference',
    'Opens at': 'Opens at',
    'Closes at': 'Closes at',
    'Immediately': 'Immediately',
    'Set': 'Set',
    'Close Homework': 'Close Homework',
    'Close Exam': 'Close Exam',
    'Students will no longer be able to submit this homework.':
        'Students will no longer be able to submit this homework.',
    'Students will no longer be able to start this exam.':
        'Students will no longer be able to start this exam.',
    'Close failed': 'Close failed',
    'This assessment has not started yet.':
        'This assessment has not started yet.',
    'The assessment time is over.': 'The assessment time is over.',
    'This assessment has been closed.': 'This assessment has been closed.',
    'This assessment is not available.': 'This assessment is not available.',
    'Not started yet': 'Not started yet',
    'Time is over': 'Time is over',
    'Total due': 'Total due',
    'Remaining': 'Remaining',
    'Mark All Read': 'Mark All Read',
    'No notifications in your inbox.': 'No notifications in your inbox.',
    'Monthly Report': 'Monthly Report',
    'Completed lessons': 'Completed lessons',
    'Cash balance': 'Cash balance',
    'Monthly attendance': 'Monthly attendance',
    'Only records inside the current month are counted here.':
        'Only records inside the current month are counted here.',
    'No attendance records in this month yet.':
        'No attendance records in this month yet.',
    'Payment follow-up': 'Payment follow-up',
    'No open cash invoices.': 'No open cash invoices.',
    'Academy alerts sent to your guardian account.':
        'Academy alerts sent to your guardian account.',
    'No notifications yet.': 'No notifications yet.',
    'No next lesson available.': 'No next lesson available.',
    'Guardian Insights': 'Guardian Insights',
    'Important follow-up points from real student data.':
        'Important follow-up points from real student data.',
    'Attendance needs follow-up': 'Attendance needs follow-up',
    'Learning progress is low': 'Learning progress is low',
    'Overdue payment': 'Overdue payment',
    'Cash payment due': 'Cash payment due',
    'Unread academy alerts': 'Unread academy alerts',
    'No urgent follow-up': 'No urgent follow-up',
    'Progress, attendance, and payments have no critical alerts.':
        'Progress, attendance, and payments have no critical alerts.',
    'Improve attendance consistency': 'Improve attendance consistency',
    'Add a fixed study block': 'Add a fixed study block',
    'Settle cash balance': 'Settle cash balance',
    'Monthly status is stable': 'Monthly status is stable',
    'No urgent attendance, progress, or payment action is needed.':
        'No urgent attendance, progress, or payment action is needed.',
    'Open tasks': 'Open tasks',
    'Students visible': 'Students visible',
    'Groups visible': 'Groups visible',
    'Recent enrollments': 'Recent enrollments',
    'Priority queue': 'Priority queue',
    'Pending items that usually need staff follow-up.':
        'Pending items that usually need staff follow-up.',
    'No priority items right now.': 'No priority items right now.',
    'No pending leave requests.': 'No pending leave requests.',
    'No invoices need follow-up.': 'No invoices need follow-up.',
    'Attendance exceptions': 'Attendance exceptions',
    'No recent absent or late records.': 'No recent absent or late records.',
    'No recent enrollments visible.': 'No recent enrollments visible.',
    'Unified operations queue': 'Unified operations queue',
    'Run the latest operations migration to enable this queue.':
        'Run the latest operations migration to enable this queue.',
    'Students Directory': 'Students Directory',
    'Groups Roster': 'Groups Roster',
    'Search groups': 'Search groups',
    'Some operations could not be loaded.':
        'Some operations could not be loaded.',
    'More issues are available in logs.': 'More issues are available in logs.',
    'Unread notifications': 'Unread notifications',
    'No access': 'No access',
    'Phone': 'Phone',
    'School': 'School',
    'Subject': 'Subject',
    'Close': 'Close',
    'students.view permission is required.':
        'students.view permission is required.',
    'groups.view permission is required.':
        'groups.view permission is required.',
    'Search Students (Name, Code, Email)':
        'Search Students (Name, Code, Email)',
    'No students found.': 'No students found.',
    'Student Code': 'Student Code',
    'Grade': 'Grade',
    'N/A': 'N/A',
    'Search Parents (Name, Email, Phone)':
        'Search Parents (Name, Email, Phone)',
    'No parents found.': 'No parents found.',
    'Parent Record': 'Parent Record',
    'Occupation': 'Occupation',
    'No teachers found.': 'No teachers found.',
    'Teacher Record': 'Teacher Record',
    'Specialization': 'Specialization',
    'General': 'General',
    'No active groups found.': 'No active groups found.',
    'Max Capacity': 'Max Capacity',
    'Unlimited': 'Unlimited',
    'No active branches found.': 'No active branches found.',
    'No address provided': 'No address provided',
    'No active subjects found.': 'No active subjects found.',
    'No description': 'No description',
    'No active schedules found.': 'No active schedules found.',
    'Day': 'Day',
    'Location': 'Location',
    'Unassigned Room': 'Unassigned Room',
    'No questions found in Question Bank.':
        'No questions found in Question Bank.',
    'Type': 'Type',
    'Points': 'Points',
    'Difficulty': 'Difficulty',
    'options': 'options',
    'No assigned homework found.': 'No assigned homework found.',
    'Due': 'Due',
    'Max Score': 'Max Score',
    'No available exams found.': 'No available exams found.',
    'Duration': 'Duration',
    'min': 'min',
    'Start': 'Start',
    'No questions configured for this exam.':
        'No questions configured for this exam.',
    'Question': 'Question',
    'of': 'of',
    'Autosaved': 'Autosaved',
    'Previous': 'Previous',
    'Next': 'Next',
    'Submit Exam': 'Submit Exam',
    'multiple_choice': 'multiple choice',
    'true_false': 'true/false',
    'short_answer': 'short answer',
    'easy': 'easy',
    'medium': 'medium',
    'hard': 'hard',
    'No invoices issued.': 'No invoices issued.',
    'Invoice': 'Invoice',
    'Total': 'Total',
    'Paid': 'Paid',
    'Status': 'Status',
    'PAID': 'PAID',
    'Record Cash': 'Record Cash',
    'Financial Summary': 'Financial Summary',
    'Total Due': 'Total Due',
    'Total Paid': 'Total Paid',
    'Balance': 'Balance',
    'Full Name': 'Full Name',
    'New Password': 'New Password',
    'At least 6 characters': 'At least 6 characters',
    'Name is required': 'Name is required',
    'Save Changes': 'Save Changes',
    'Change Password': 'Change Password',
    'Update': 'Update',
    'Account Profile': 'Account Profile',
    'Sign Out': 'Sign Out',
    'User': 'User',
    'Email Address': 'Email Address',
    'Branch Assignment': 'Branch Assignment',
    'Provision New Student Account': 'Provision New Student Account',
    'Provision Student': 'Provision Student',
    'Student Management': 'Student Management',
    'Provision student accounts and review academy enrollment data.':
        'Provision student accounts and review academy enrollment data.',
    'Search students': 'Search students',
    'No students found': 'No students found',
    'Provision students from here after branches exist.':
        'Provision students from here after branches exist.',
    'Login QR': 'Login QR',
    'Code': 'Code',
    'Email': 'Email',
    'Provision New Teacher Account': 'Provision New Teacher Account',
    'Provision Teacher': 'Provision Teacher',
    'Teacher Management': 'Teacher Management',
    'Provision teachers and monitor their subject assignments.':
        'Provision teachers and monitor their subject assignments.',
    'Search teachers': 'Search teachers',
    'No teachers found': 'No teachers found',
    'Provision teacher accounts after branches exist.':
        'Provision teacher accounts after branches exist.',
    'Provision New Parent Account': 'Provision New Parent Account',
    'Provision Parent': 'Provision Parent',
    'Parent Management': 'Parent Management',
    'Provision guardian accounts and link them to students.':
        'Provision guardian accounts and link them to students.',
    'Search parents': 'Search parents',
    'No parents found': 'No parents found',
    'Provision guardian accounts, then link children.':
        'Provision guardian accounts, then link children.',
    'Select Child / Student': 'Select Child / Student',
    'Relationship Type': 'Relationship Type',
    'Father': 'Father',
    'Mother': 'Mother',
    'Guardian': 'Guardian',
    'Link Child': 'Link Child',
    'Provision Staff / Admin Account': 'Provision Staff / Admin Account',
    'Target Role': 'Target Role',
    'Operations Staff': 'Operations Staff',
    'Branch Admin': 'Branch Admin',
    'Provision Account': 'Provision Account',
    'Staff & Admin Management': 'Staff & Admin Management',
    'Provision operations staff and branch admin accounts.':
        'Provision operations staff and branch admin accounts.',
    'Provision Staff': 'Provision Staff',
    'No staff accounts found': 'No staff accounts found',
    'Provision staff or admin users from here.':
        'Provision staff or admin users from here.',
    'Role': 'Role',
    'No enrolled students in this group.':
        'No enrolled students in this group.',
    'Roll Call': 'Roll Call',
    'Finalize': 'Finalize',
    'Attendance finalized.': 'Attendance finalized.',
    'Attendance finalized': 'Attendance finalized',
    'Finalization error': 'Finalization error',
    'Teacher Daily Attendance Workspace': 'Teacher Daily Attendance Workspace',
    'No assigned groups found.': 'No assigned groups found.',
    'No active class sessions for this group.':
        'No active class sessions for this group.',
    'Main Hall': 'Main Hall',
    'Date': 'Date',
    'Open session board': 'Open session board',
    'Show rotating attendance QR': 'Show rotating attendance QR',
    'FINALIZED': 'FINALIZED',
    'Take Attendance': 'Take Attendance',
    'Finalize QR attendance?': 'Finalize QR attendance?',
    'Students who did not scan the QR will be marked absent and this session will be completed.':
        'Students who did not scan the QR will be marked absent and this session will be completed.',
    'Finalization failed': 'Finalization failed',
    'Attendance QR': 'Attendance QR',
    'Students scan this QR to mark themselves present. It rotates every minute.':
        'Students scan this QR to mark themselves present. It rotates every minute.',
    'Waiting for token': 'Waiting for token',
    'Expires in': 'Expires in',
    'Checked in': 'Checked in',
    'Roster will appear here.': 'Roster will appear here.',
    'Manual': 'Manual',
    'Finalize Attendance': 'Finalize Attendance',
    'Assigned group': 'Assigned group',
    'Attendance marked successfully.': 'Attendance marked successfully.',
    'Attendance was not accepted.': 'Attendance was not accepted.',
    'Attendance scan failed': 'Attendance scan failed',
    'Scan Attendance QR': 'Scan Attendance QR',
    'Scan the QR shown by your teacher. The code changes every minute.':
        'Scan the QR shown by your teacher. The code changes every minute.',
    'Manual token': 'Manual token',
    'Submit Token': 'Submit Token',
    'Board saved.': 'Board saved.',
    'Session Board': 'Session Board',
    'Published': 'Published',
    'Publish': 'Publish',
    'Pen': 'Pen',
    'Eraser': 'Eraser',
    'Clear': 'Clear',
    'No class sessions scheduled today.': 'No class sessions scheduled today.',
    'Mark All Present': 'Mark All Present',
    'Group Session': 'Group Session',
    'Student ID': 'Student ID',
    'Current': 'Current',
    'Save Roll Call': 'Save Roll Call',
    'Finalize Roll Call': 'Finalize Roll Call',
    'Attendance Summary': 'Attendance Summary',
    'Rate': 'Rate',
    'Excused': 'Excused',
    'Create an active subject first.': 'Create an active subject first.',
    'Create Semester': 'Create Semester',
    'Semester Name (e.g. Fall 2026)': 'Semester Name (e.g. Fall 2026)',
    'Semester Code (e.g. FALL-2026)': 'Semester Code (e.g. FALL-2026)',
    'Failed to create semester': 'Failed to create semester',
    'Create Unit in': 'Create Unit in',
    'Unit Name (e.g. Unit 1: Algorithms)':
        'Unit Name (e.g. Unit 1: Algorithms)',
    'Unit Code (e.g. U1-ALG)': 'Unit Code (e.g. U1-ALG)',
    'Failed to create unit': 'Failed to create unit',
    'Create Unit': 'Create Unit',
    'Create Lesson in': 'Create Lesson in',
    'Lesson Title': 'Lesson Title',
    'Lesson Type': 'Lesson Type',
    'Video': 'Video',
    'PDF / Document': 'PDF / Document',
    'Interactive Quiz': 'Interactive Quiz',
    'Failed to create lesson': 'Failed to create lesson',
    'Create Lesson': 'Create Lesson',
    'Attach PDF Resource': 'Attach PDF Resource',
    'Resource Title': 'Resource Title',
    'Storage object path': 'Storage object path',
    'Attach Resource': 'Attach Resource',
    'PDF resource attached!': 'PDF resource attached!',
    'Upload failed': 'Upload failed',
    'No semesters found. Add a semester to start.':
        'No semesters found. Add a semester to start.',
    'Units': 'Units',
    'Add Unit': 'Add Unit',
    'Add Lesson': 'Add Lesson',
    'Attachments': 'Attachments',
    'Upload Private PDF Resource': 'Upload Private PDF Resource',
    'Toggle Publish': 'Toggle Publish',
    'Path': 'Path',
    'Template copied': 'Template copied',
    'Import type': 'Import type',
    'No file selected': 'No file selected',
    'valid': 'valid',
    'done': 'done',
    'issues': 'issues',
    'Importing': 'Importing',
    'Import valid rows': 'Import valid rows',
    'Choose a CSV or Excel file to preview before importing.':
        'Choose a CSV or Excel file to preview before importing.',
    'The first worksheet is imported. Keep the first row as headers matching the template.':
        'The first worksheet is imported. Keep the first row as headers matching the template.',
    'Row': 'Row',
    'Name': 'Name',
    'Branch ID': 'Branch ID',
    'Message': 'Message',
    'Ready': 'Ready',
    'Invalid': 'Invalid',
    'Imported': 'Imported',
    'Failed': 'Failed',
    'Missing full_name': 'Missing full_name',
    'Invalid email': 'Invalid email',
    'branch_id must be a UUID': 'branch_id must be a UUID',
    'Session Roster': 'Session Roster',
    'Failed to load roster': 'Failed to load roster',
    'Attendance recorded & finalized!': 'Attendance recorded & finalized!',
    'Recording failed': 'Recording failed',
    'Save Attendance': 'Save Attendance',
    'Review Leave Request': 'Review Leave Request',
    'Leave request rejected.': 'Leave request rejected.',
    'Review failed': 'Review failed',
    'Reject': 'Reject',
    'Leave request approved!': 'Leave request approved!',
    'Approve': 'Approve',
    'Sessions & Rosters': 'Sessions & Rosters',
    'Leave Requests': 'Leave Requests',
    'No class sessions found for this group.':
        'No class sessions found for this group.',
    'No location assigned': 'No location assigned',
    'Leave Request': 'Leave Request',
    'Upload PDF': 'Upload PDF',
    'Choose PDF': 'Choose PDF',
    'No PDF selected.': 'No PDF selected.',
    'Selected': 'Selected',
    'Upload & Attach': 'Upload & Attach',
    'PDF uploaded and attached.': 'PDF uploaded and attached.',
    'Academic Curriculum Hierarchy': 'Academic Curriculum Hierarchy',
    'No semesters found for your taught subjects.':
        'No semesters found for your taught subjects.',
    'Upload Resource': 'Upload Resource',
    'Code Challenges': 'Code Challenges',
    'Published challenges appear in the student code workspace.':
        'Published challenges appear in the student code workspace.',
    'No challenges created for this lesson yet.':
        'No challenges created for this lesson yet.',
    'Create Challenge': 'Create Challenge',
    'Title': 'Title',
    'Description': 'Description',
    'XP': 'XP',
    'Add Test Case': 'Add Test Case',
    'Test Case': 'Test Case',
    'Hidden': 'Hidden',
    'Case Name': 'Case Name',
    'Input stdin': 'Input stdin',
    'Expected stdout': 'Expected stdout',
    'Create New Group': 'Create New Group',
    'Group Name (e.g. Programming Level 1)':
        'Group Name (e.g. Programming Level 1)',
    'Group Code (e.g. GRP-PROG1)': 'Group Code (e.g. GRP-PROG1)',
    'Branch': 'Branch',
    'Failed to create group': 'Failed to create group',
    'Create Group': 'Create Group',
    'Enroll Student in Group': 'Enroll Student in Group',
    'Select Student': 'Select Student',
    'Group price (EGP)': 'Group price (EGP)',
    'Discount / exemption (EGP)': 'Discount / exemption (EGP)',
    'Content stays locked until the cash invoice is fully paid. If final price is 0, access is activated as an exemption.':
        'Content stays locked until the cash invoice is fully paid. If final price is 0, access is activated as an exemption.',
    'Student enrolled. Content is pending cash payment.':
        'Student enrolled. Content is pending cash payment.',
    'Student enrolled with payment exemption.':
        'Student enrolled with payment exemption.',
    'Enrollment failed': 'Enrollment failed',
    'Assign Teacher to Group': 'Assign Teacher to Group',
    'Select Teacher': 'Select Teacher',
    'Primary Teacher': 'Primary Teacher',
    'Co-Teacher': 'Co-Teacher',
    'Teacher assigned successfully!': 'Teacher assigned successfully!',
    'Teacher assignment failed': 'Teacher assignment failed',
    'Assign Teacher': 'Assign Teacher',
    'Capacity': 'Capacity',
    'Back': 'Back',
    'Enrolled Students': 'Enrolled Students',
    'Assigned Teachers': 'Assigned Teachers',
    'No enrolled students.': 'No enrolled students.',
    'No assigned teachers.': 'No assigned teachers.',
    'Assign': 'Assign',
    'Create New Branch': 'Create New Branch',
    'Branch Name (e.g. Nasr City)': 'Branch Name (e.g. Nasr City)',
    'Branch Code (e.g. NASR-01)': 'Branch Code (e.g. NASR-01)',
    'Address': 'Address',
    'Phone Number': 'Phone Number',
    'Failed to create branch': 'Failed to create branch',
    'Create Branch': 'Create Branch',
    'Edit Branch': 'Edit Branch',
    'Branch Name': 'Branch Name',
    'Branch Code': 'Branch Code',
    'Branch updated successfully!': 'Branch updated successfully!',
    'Failed to update branch': 'Failed to update branch',
    'Create New Subject': 'Create New Subject',
    'Subject Name (e.g. Programming Fundamentals)':
        'Subject Name (e.g. Programming Fundamentals)',
    'Subject Code (e.g. CS-101)': 'Subject Code (e.g. CS-101)',
    'Failed to create subject': 'Failed to create subject',
    'Create Subject': 'Create Subject',
    'Edit Subject': 'Edit Subject',
    'Subject Name': 'Subject Name',
    'Subject Code': 'Subject Code',
    'Subject updated successfully!': 'Subject updated successfully!',
    'Failed to update subject': 'Failed to update subject',
    'Create Homework for': 'Create Homework for',
    'Homework title': 'Homework title',
    'Instructions': 'Instructions',
    'Max score': 'Max score',
    'Homework published.': 'Homework published.',
    'Creation failed': 'Creation failed',
    'Teacher Homework Workspace': 'Teacher Homework Workspace',
    'Create Homework': 'Create Homework',
    'No homework assignments published yet.':
        'No homework assignments published yet.',
    'Create Exam for': 'Create Exam for',
    'Exam title': 'Exam title',
    'Duration minutes': 'Duration minutes',
    'Pass score': 'Pass score',
    'Exam published.': 'Exam published.',
    'Teacher Exam & Quiz Workspace': 'Teacher Exam & Quiz Workspace',
    'Create Exam': 'Create Exam',
    'No exams published yet.': 'No exams published yet.',
    'Pass Score': 'Pass Score',
    'Manual Grading & Feedback': 'Manual Grading & Feedback',
    'Final Score': 'Final Score',
    'Teacher Feedback': 'Teacher Feedback',
    'Grade & feedback submitted to student!':
        'Grade & feedback submitted to student!',
    'Grading failed': 'Grading failed',
    'Submit Grade': 'Submit Grade',
    'Submissions & Manual Grading Queue': 'Submissions & Manual Grading Queue',
    'No pending submissions requiring manual grading.':
        'No pending submissions requiring manual grading.',
    'Learner': 'Learner',
    'Score': 'Score',
    'Pending': 'Pending',
    'No assigned teaching groups found.': 'No assigned teaching groups found.',
    'Create MCQ Question with Answer Key':
        'Create MCQ Question with Answer Key',
    'Question Prompt (e.g. What is 2 + 2?)':
        'Question Prompt (e.g. What is 2 + 2?)',
    'Option 1': 'Option 1',
    'Option 2': 'Option 2',
    'Option 3': 'Option 3',
    'Option 4': 'Option 4',
    'Correct Option (Answer Key)': 'Correct Option (Answer Key)',
    'Option 1 is Correct': 'Option 1 is Correct',
    'Option 2 is Correct': 'Option 2 is Correct',
    'Option 3 is Correct': 'Option 3 is Correct',
    'Option 4 is Correct': 'Option 4 is Correct',
    'Default Points': 'Default Points',
    'MCQ Question & Answer Key saved to Question Bank!':
        'MCQ Question & Answer Key saved to Question Bank!',
    'Save MCQ Question': 'Save MCQ Question',
    'Teacher Question Bank': 'Teacher Question Bank',
    'Add MCQ Question': 'Add MCQ Question',
    'Teaching Group': 'Teaching Group',
    'Open a group to review students and request discounts.':
        'Open a group to review students and request discounts.',
    'unpaid': 'unpaid',
    'Final': 'Final',
    'pending request': 'pending request',
    'Request discount or exemption': 'Request discount or exemption',
    'Request adjustment for': 'Request adjustment for',
    'Discount amount': 'Discount amount',
    'Use': 'Use',
    'for full exemption.': 'for full exemption.',
    'Enter a valid amount': 'Enter a valid amount',
    'Discount cannot exceed final price': 'Discount cannot exceed final price',
    'Send request': 'Send request',
    'Adjustment request sent.': 'Adjustment request sent.',
    'Helpdesk': 'Helpdesk',
    'Helpdesk Ticketing': 'Helpdesk Ticketing',
    'Manage your support tickets and requests':
        'Manage your support tickets and requests',
    'Manage support requests for you and your children.':
        'Manage support requests for you and your children.',
    'Manage your technical support requests.':
        'Manage your technical support requests.',
    'Manage user support requests and technical issues.':
        'Manage user support requests and technical issues.',
    'Create Ticket': 'Create Ticket',
    'New Ticket': 'New Ticket',
    'Create Support Ticket': 'Create Support Ticket',
    'No tickets yet': 'No tickets yet',
    'Create a ticket to get help with your courses or account.':
        'Create a ticket to get help with your courses or account.',
    'No tickets found in this category.': 'No tickets found in this category.',
    'Unable to load support tickets. Please try again.':
        'Unable to load support tickets. Please try again.',
    'Briefly describe the issue': 'Briefly describe the issue',
    'Provide details...': 'Provide details...',
    'Related Group/Class': 'Related Group/Class',
    'Submit Ticket': 'Submit Ticket',
    'No replies yet': 'No replies yet',
    'Type your reply...': 'Type your reply...',
    'Open': 'Open',
    'In Progress': 'In Progress',
    'Closed': 'Closed',
    'User ID': 'User ID',
    'Submitted': 'Submitted',
    'Activity': 'Activity',
    'System': 'System',
    'Ticket logged successfully.': 'Ticket logged successfully.',
    'Reply feature is coming soon!': 'Reply feature is coming soon!',
    'low': 'low',
    'normal': 'normal',
    'high': 'high',
    'urgent': 'urgent',
    'Low': 'Low',
    'Normal': 'Normal',
    'High': 'High',
    'Urgent': 'Urgent',
  };

  static const Map<String, String> _ar = {
    'settings': 'الإعدادات',
    'language': 'اللغة',
    'english': 'الإنجليزية',
    'arabic': 'العربية',
    'app_settings': 'إعدادات التطبيق',
    'display_language': 'لغة العرض',
    'display_language_subtitle': 'اختر اللغة المستخدمة داخل التطبيق.',
    'notifications': 'الإشعارات',
    'push_notifications': 'إشعارات الهاتف',
    'push_notifications_subtitle':
        'استقبل تنبيهات فورية حقيقية من Firebase Cloud Messaging.',
    'enabled': 'مفعلة',
    'disabled': 'غير مفعلة',
    'close': 'إغلاق',
    'save': 'حفظ',
    'retry': 'إعادة المحاولة',
    'refresh': 'تحديث',
    'sign_out': 'تسجيل الخروج',
    'Opening student portal': 'فتح تطبيق الطالب',
    'Checking your session, preferences, and secure access.':
        'جاري فحص الجلسة والإعدادات وتأمين الدخول.',
    'Opening teacher portal': 'فتح تطبيق المدرس',
    'Preparing classes, workspace, and secure access.':
        'جاري تجهيز الفصول ومساحة العمل وتأمين الدخول.',
    'Opening guardian portal': 'فتح تطبيق ولي الأمر',
    'Loading linked children, alerts, and secure access.':
        'جاري تحميل الأبناء المرتبطين والتنبيهات وتأمين الدخول.',
    'Opening admin dashboard': 'فتح لوحة تحكم الإدارة',
    'Loading management tools, permissions, and secure access.':
        'جاري تحميل أدوات الإدارة والصلاحيات وتأمين الدخول.',
    'Opening staff portal': 'فتح تطبيق الموظفين',
    'Loading operations, permissions, and secure access.':
        'جاري تحميل العمليات والصلاحيات وتأمين الدخول.',
    'Secure unlock': 'فتح آمن',
    'Checking your fingerprint and preparing the academy portal.':
        'جاري فحص البصمة وتجهيز التطبيق.',
    'Preparing lesson workspace...': 'جاري تجهيز مساحة الدرس...',
    'Loading your notes and saved board...':
        'جاري تحميل ملاحظاتك والبورد المحفوظ...',
    'Downloading lesson PDF...': 'جاري تحميل ملف الدرس...',
    'Syncing teacher board and your workspace...':
        'جاري مزامنة شرح المدرس ومساحتك...',
    'Run': 'تشغيل',
    'Terminal Output': 'نتيجة التشغيل',
    'Starter code': 'كود جاهز',
    'Format': 'تنسيق',
    'Preparing sandbox': 'تجهيز بيئة التشغيل',
    'Compiling': 'جاري الترجمة',
    'Finished': 'انتهى',
    'Stopped': 'توقف',
    'The PDF could not be downloaded. Please check the file link and try again.':
        'تعذر تحميل ملف الدرس. تأكد من رابط الملف وحاول مرة أخرى.',
    'The PDF download took too long. Please check your connection and try again.':
        'استغرق تحميل ملف الدرس وقتا طويلا. تأكد من الاتصال وحاول مرة أخرى.',
    'The PDF could not be opened. Please check your connection and try again.':
        'تعذر فتح ملف الدرس. تأكد من الاتصال وحاول مرة أخرى.',
    'startup_failed': 'فشل تشغيل التطبيق',
    'academy_platform': 'منصة الأكاديمية',
    'admin_dashboard': 'الأكاديمية - لوحة الإدارة',
    'student_portal': 'الأكاديمية - تطبيق الطالب',
    'Appearance': 'المظهر',
    'Theme Mode': 'وضع المظهر',
    'Choose between Light, Dark, or System theme.':
        'اختر بين المظهر الفاتح، الداكن أو التلقائي للنظام.',
    'Auto': 'تلقائي',
    'Light': 'فاتح',
    'Dark': 'داكن',
    'Animation Quality': 'جودة الحركة (الأنيميشن)',
    'Use 120fps fluid animations':
        'تفعيل حركة فائقة النعومة بمعدل 120 إطار بالثانية',
    'Localization': 'اللغة والمنطقة',
    'Time Zone': 'المنطقة الزمنية',
    'Automatic': 'تلقائي',
    'Notifications & Alerts': 'الإشعارات والتنبيهات',
    'Email Digest': 'الملخص البريدي',
    'Receive daily summary of activities':
        'استلام ملخص يومي بالأنشطة على البريد الإلكتروني',
    'Security & Privacy': 'الأمان والخصوصية',
    'Two-Factor Authentication': 'المصادقة الثنائية (2FA)',
    'Require 2FA for all admin logins':
        'طلب المصادقة الثنائية عند كل تسجيل دخول للإدارة',
    'Data Collection': 'جمع بيانات الاستخدام',
    'Send anonymous usage data to improve the app':
        'إرسال بيانات استخدام مجهولة الهوية لتحسين التطبيق',
    'Got it': 'موافق',
    'Biometric Login': 'تسجيل الدخول بالبصمة',
    'Use FaceID/TouchID for quick access':
        'استخدام بصمة الوجه/الإصبع للدخول السريع',
    'Student Portal': 'تطبيق الطالب',
    'Welcome back': 'مرحباً بعودتك',
    'Active Courses': 'المجموعات النشطة',
    'Overall XP': 'نقاط الخبرة (XP)',
    'Completed Lessons': 'الدروس المكتملة',
    'Attendance Rate': 'نسبة الحضور',
    'Next Up': 'الدرس القادم',
    'Start Lesson': 'ابدأ الدرس الآن',
    'No upcoming lessons': 'لا توجد دروس قادمة حالياً',
    'Enrolled Groups': 'المجموعات المسجلة',
    'Financial Summary': 'الملخص المالي',
    'Total Invoiced': 'إجمالي المطالبات',
    'Total Paid': 'إجمالي المدفوع',
    'Outstanding Balance': 'المبلغ المتبقي',
    'Homework Feed': 'قائمة الواجبات',
    'Exams & Quizzes': 'الامتحانات والاختبارات',
    'Attendance History': 'سجل الحضور والغياب',
    'Request Leave': 'طلب إجازة',
    'General leave request': 'طلب إجازة عامة',
    'Reason': 'السبب / العذر',
    'Leave request sent.': 'تم إرسال طلب الإجازة بنجاح.',
    'Answer / notes': 'الإجابة أو الملاحظات',
    'Attachment URL': 'رابط المرفقات',
    'Homework submitted.': 'تم تسليم الواجب بنجاح.',
    'Scan QR Attendance': 'تسجيل الحضور عبر QR',
    'No attendance history recorded yet.': 'لا يوجد سجل حضور مسجل حتى الآن.',
    'No leave requests submitted yet.': 'لم يتم تقديم أي طلبات إجازة.',
    'Invoices': 'الفواتير والرسوم',
    'Receipts': 'إيصالات السداد',
    'No invoices found.': 'لا توجد فواتير مسجلة.',
    'No receipts found.': 'لا توجد إيصالات سداد.',
    'No announcements published yet.': 'لا توجد إعلانات منشورة حالياً.',
    'No notifications yet.': 'لا توجد إشعارات جديدة.',
    'Mark all read': 'تحديد الكل كقروء',
    'Session Boards': 'سبورات الحصص التفاعلية',
    'No published session boards yet.': 'لا توجد سبورات حصص منشورة حتى الآن.',
    'Acknowledge': 'تأكيد الاطلاع',
    'Acknowledged': 'تم الاطلاع',
    'Paid': 'مدفوع',
    'Pending': 'معلق',
    'Overdue': 'متأخر',
    'Partially Paid': 'مدفوع جزئياً',
    'Present': 'حاضر',
    'Absent': 'غائب',
    'Late': 'متأخر',
    'Excused': 'معذور',
    'Approved': 'مقبول',
    'Rejected': 'مرفوض',
    'Session': 'الحصة / الجلسة',

    'teacher_portal': 'الأكاديمية - تطبيق المدرس',
    'parent_portal': 'الأكاديمية - تطبيق ولي الأمر',
    'staff_portal': 'الأكاديمية - تطبيق الموظفين',
    'Overview': 'نظرة عامة',
    'Home': 'الرئيسية',
    'Classes': 'المجموعات',
    'Workspace': 'مساحة العمل',
    'Analytics': 'التحليلات',
    'Branches': 'الفروع',
    'Subjects': 'المواد',
    'Groups': 'المجموعات',
    'Schedules': 'الجداول',
    'Students': 'الطلاب',
    'Parents': 'أولياء الأمور',
    'Teachers': 'المدرسون',
    'Staff': 'الموظفون',
    'Curriculum': 'المناهج',
    'Questions': 'الأسئلة',
    'Homework': 'الواجبات',
    'Exams': 'الاختبارات',
    'Attendance': 'الحضور',
    'Finance': 'المالية',
    'Security': 'الصلاحيات',
    'Audit': 'سجل العمليات',
    'Replay': 'إعادة الشرح',
    'Import': 'استيراد',
    'Settings': 'الإعدادات',
    'Lessons': 'الدروس',
    'Assessments': 'التقييمات',
    'Boards': 'البوردات',
    'Announcements': 'الإعلانات',
    'Billing': 'الفواتير',
    'Account': 'الحساب',
    'Progress': 'التقدم',
    'Payments': 'المدفوعات',
    'Report': 'التقرير',
    'Teaching': 'التدريس',
    'Academic': 'الأكاديمي',
    'Operations': 'العمليات',
    'Queues': 'الطوابير',
    'Notifications': 'الإشعارات',
    'Reports': 'التقارير',
    'Academy Suite': 'نظام الأكاديمية',
    'Admin operations': 'عمليات الإدارة',
    'Student portal': 'تطبيق الطالب',
    'Teacher Studio': 'استوديو المدرس',
    'Teaching workspace': 'مساحة التدريس',
    'Operations workspace': 'مساحة العمليات',
    'Admin': 'الإدارة',
    'Clear search': 'مسح البحث',
    'Search': 'بحث',
    'Create': 'إنشاء',
    'Edit': 'تعديل',
    'Delete': 'حذف',
    'Actions': 'الإجراءات',
    'Add Exam': 'إضافة امتحان',
    'Add Homework': 'إضافة واجب',
    'Add Question': 'إضافة سؤال',
    'Are you sure you want to delete this exam?':
        'هل أنت متأكد من حذف هذا الامتحان؟',
    'Are you sure you want to delete this homework?':
        'هل أنت متأكد من حذف هذا الواجب؟',
    'Are you sure you want to delete this question?':
        'هل أنت متأكد من حذف هذا السؤال؟',
    'Create Homework Assignment': 'إنشاء واجب جديد',
    'Create New Exam': 'إنشاء امتحان جديد',
    'Create Question': 'إنشاء سؤال',
    'Create an active group first.': 'أنشئ مجموعة نشطة أولا.',
    'Create reusable assessment questions by subject.':
        'إنشاء أسئلة قابلة لإعادة الاستخدام حسب المادة.',
    'Delete Exam': 'حذف الامتحان',
    'Delete Homework': 'حذف الواجب',
    'Delete Question': 'حذف السؤال',
    'Duration (Minutes)': 'المدة بالدقائق',
    'Edit Exam': 'تعديل الامتحان',
    'Edit Homework': 'تعديل الواجب',
    'Edit Homework Assignment': 'تعديل الواجب',
    'Edit Question': 'تعديل السؤال',
    'Exam & Quiz Management': 'إدارة الامتحانات والاختبارات',
    'Exam Title': 'عنوان الامتحان',
    'Exam published successfully!': 'تم نشر الامتحان بنجاح!',
    'Exam report generated.': 'تم إنشاء تقرير الامتحان.',
    'Exam updated successfully!': 'تم تحديث الامتحان بنجاح!',
    'Failed to close': 'فشل القفل',
    'Failed to delete': 'فشل الحذف',
    'Failed to generate report': 'فشل إنشاء التقرير',
    'Homework Management': 'إدارة الواجبات',
    'Homework Title': 'عنوان الواجب',
    'Homework assignment published!': 'تم نشر الواجب بنجاح!',
    'Homework updated successfully!': 'تم تحديث الواجب بنجاح!',
    'Instructions / Description': 'التعليمات / الوصف',
    'Max Score / Points': 'الدرجة النهائية',
    'Multiple Choice (MCQ)': 'اختيار من متعدد',
    'No active subject found.': 'لا توجد مادة نشطة.',
    'No exam data': 'لا توجد بيانات امتحانات',
    'No exams found.': 'لا توجد امتحانات.',
    'No homework assignments found.': 'لا توجد واجبات.',
    'No homework data': 'لا توجد بيانات واجبات',
    'No question data': 'لا توجد بيانات أسئلة',
    'No questions found in question bank.': 'لا توجد أسئلة في بنك الأسئلة.',
    'Passing Score': 'درجة النجاح',
    'Publish Exam': 'نشر الامتحان',
    'Publish Homework': 'نشر الواجب',
    'Publish group assignments with due dates and scoring.':
        'نشر واجبات المجموعات مع مواعيد التسليم والدرجات.',
    'Publish group exams with explicit duration and scoring.':
        'نشر امتحانات المجموعات بمدة ودرجات واضحة.',
    'Question Bank': 'بنك الأسئلة',
    'Question Prompt / Text': 'نص السؤال',
    'Question Type': 'نوع السؤال',
    'Question created!': 'تم إنشاء السؤال!',
    'Question updated!': 'تم تحديث السؤال!',
    'Select due date': 'اختر موعد التسليم',
    'Short Answer': 'إجابة قصيرة',
    'True / False': 'صح / خطأ',
    'Update failed': 'فشل التحديث',
    'View Submissions': 'عرض التسليمات',
    'View': 'عرض',
    'Export': 'تصدير',
    'Upload': 'رفع',
    'Download': 'تحميل',
    'Request': 'طلب',
    'Submit': 'إرسال',
    'Cancel': 'إلغاء',
    'Send': 'إرسال',
    'Mark read': 'تحديد كمقروء',
    'Save Profile': 'حفظ الملف الشخصي',
    'Update Password': 'تحديث كلمة المرور',
    'No lessons available': 'لا توجد دروس متاحة',
    'Lessons appear here after your teacher publishes them.':
        'ستظهر الدروس هنا بعد أن ينشرها المدرس.',
    'No assessments available': 'لا توجد تقييمات متاحة',
    'Published homework and exams will appear here.':
        'ستظهر الواجبات والاختبارات المنشورة هنا.',
    'No attendance records': 'لا توجد سجلات حضور',
    'Attendance appears after sessions are marked.':
        'يظهر الحضور بعد تسجيله في الحصص.',
    'No published boards': 'لا توجد بوردات منشورة',
    'No announcements': 'لا توجد إعلانات',
    'Targeted announcements will appear here.': 'ستظهر الإعلانات الموجهة هنا.',
    'No notifications': 'لا توجد إشعارات',
    'Academic and payment alerts will appear here.':
        'ستظهر تنبيهات الدراسة والدفع هنا.',
    'No billing records': 'لا توجد سجلات فواتير',
    'Invoices appear here when a subscription is assigned.':
        'ستظهر الفواتير هنا عند إضافة اشتراك.',
    'No operations data': 'لا توجد بيانات عمليات',
    'Refresh after staff permissions are assigned.':
        'حدث الصفحة بعد تعيين صلاحيات الموظف.',
    'No linked children': 'لا يوجد طلاب مرتبطون',
    'Ask the academy admin to link your account to a student profile.':
        'اطلب من إدارة الأكاديمية ربط حسابك بملف الطالب.',
    'Teacher Portal': 'تطبيق المدرس',
    'My Teaching Workspaces': 'مساحات التدريس الخاصة بي',
    'Academic & Content Workspace': 'مساحة المحتوى الأكاديمي',
    'Operations & Grading Workspace': 'مساحة العمليات والتصحيح',
    'Class Details': 'تفاصيل الحصة',
    'Student Roster': 'قائمة الطلاب',
    'No replay sessions': 'لا توجد جلسات إعادة عرض',
    'Replay data appears after students open lessons.':
        'تظهر بيانات إعادة العرض بعد فتح الطلاب للدروس.',
    'Select a replay session.': 'اختر جلسة إعادة عرض.',
    'No events were recorded.': 'لم يتم تسجيل أي أحداث.',
    'Pause replay': 'إيقاف إعادة العرض مؤقتا',
    'Play replay': 'تشغيل إعادة العرض',
    'Now': 'الآن',
    'pages': 'صفحات',
    'Failed to create session': 'فشل إنشاء الحصة',
    'Full name': 'الاسم الكامل',
    'Phone number': 'رقم الهاتف',
    'Avatar image URL': 'رابط صورة الحساب',
    'New password': 'كلمة المرور الجديدة',
    'Reviewer note': 'ملاحظة المراجع',
    'Notes': 'ملاحظات',
    'Resolution note': 'ملاحظة الحل',
    'Class session': 'الحصة',
    'Child': 'الطالب',
    'active': 'نشط',
    'paid': 'مدفوع',
    'published': 'منشور',
    'pending': 'قيد الانتظار',
    'archived': 'مؤرشف',
    'suspended': 'موقوف',
    'issued': 'صادرة',
    'overdue': 'متأخرة',
    'partially_paid': 'مدفوعة جزئيا',
    'present': 'حاضر',
    'absent': 'غائب',
    'late': 'متأخر',
    'excused': 'بعذر',
    'approved': 'مقبول',
    'rejected': 'مرفوض',
    'submitted': 'تم التسليم',
    'graded': 'تم التصحيح',
    'failed': 'فشل',
    'unknown': 'غير معروف',
    'PDF': 'PDF',
    'Lesson': 'درس',
    'Group': 'مجموعة',
    'Student': 'طالب',
    'Staff Member': 'موظف',
    'Operations Portal': 'بوابة العمليات',
    'Students, groups, attendance, leave, and payments':
        'الطلاب والمجموعات والحضور والغياب والمدفوعات',
    'Guardian Portal': 'بوابة ولي الأمر',
    'Parent overview': 'نظرة ولي الأمر',
    'linked children': 'طلاب مرتبطون',
    'active groups': 'مجموعات نشطة',
    'General request': 'طلب عام',
    'Leave request': 'طلب غياب',
    'No date': 'لا يوجد تاريخ',
    'Your learning workspace opens only from published lessons assigned to your active groups.':
        'مساحة المذاكرة تفتح فقط من الدروس المنشورة للمجموعات النشطة الخاصة بك.',
    'No lesson ready': 'لا يوجد درس جاهز',
    'Resume lesson': 'استكمال الدرس',
    'No published lesson is available.': 'لا يوجد درس منشور متاح.',
    'Enroll the student and publish curriculum content to start.':
        'أضف الطالب وانشر محتوى المنهج للبدء.',
    'You are enrolled, but no published lessons are available yet.':
        'أنت مضاف في مجموعة، لكن لا توجد دروس منشورة حتى الآن.',
    'You are not enrolled in any active group yet.':
        'لم يتم إضافتك لأي مجموعة نشطة بعد.',
    'Lesson progress': 'تقدم الدروس',
    'Attendance rate': 'نسبة الحضور',
    'Balance due': 'المبلغ المتبقي',
    'Unread alerts': 'تنبيهات غير مقروءة',
    'Active groups': 'المجموعات النشطة',
    'Groups currently assigned to the selected child.':
        'المجموعات المرتبطة حاليا بالطالب المختار.',
    'No active groups for this child.': 'لا توجد مجموعات نشطة لهذا الطالب.',
    'Next learning item': 'العنصر التعليمي التالي',
    'Published lessons': 'الدروس المنشورة',
    'Progress is calculated from the student reading history.':
        'يتم حساب التقدم من سجل مذاكرة الطالب.',
    'No published lessons available for this child yet.':
        'لا توجد دروس منشورة لهذا الطالب حتى الآن.',
    'Leave requests': 'طلبات الغياب',
    'Submit and track absence excuses.': 'إرسال ومتابعة أعذار الغياب.',
    'No invoices issued for this child.': 'لا توجد فواتير لهذا الطالب.',
    'Receipt': 'إيصال',
    'Electronic Receipt': 'إيصال إلكتروني',
    'No payment receipts generated yet.': 'لا توجد إيصالات دفع حتى الآن.',
    'Amount Paid': 'المبلغ المدفوع',
    'Issued': 'تاريخ الإصدار',
    'Reference': 'المرجع',
    'Opens at': 'يفتح في',
    'Closes at': 'يغلق في',
    'Immediately': 'فورًا',
    'Set': 'تحديد',
    'Close Homework': 'قفل الواجب',
    'Close Exam': 'قفل الامتحان',
    'Students will no longer be able to submit this homework.':
        'لن يستطيع الطلاب تسليم هذا الواجب بعد الآن.',
    'Students will no longer be able to start this exam.':
        'لن يستطيع الطلاب بدء هذا الامتحان بعد الآن.',
    'Close failed': 'فشل القفل',
    'This assessment has not started yet.': 'هذا التقييم لم يبدأ بعد.',
    'The assessment time is over.': 'انتهى وقت التقييم.',
    'This assessment has been closed.': 'تم قفل هذا التقييم.',
    'This assessment is not available.': 'هذا التقييم غير متاح.',
    'Not started yet': 'لم يبدأ بعد',
    'Time is over': 'انتهى الوقت',
    'Total due': 'إجمالي المستحق',
    'Remaining': 'المتبقي',
    'Mark All Read': 'تحديد الكل كمقروء',
    'No notifications in your inbox.': 'لا توجد إشعارات في صندوقك.',
    'Monthly Report': 'التقرير الشهري',
    'Completed lessons': 'الدروس المكتملة',
    'Cash balance': 'رصيد الكاش',
    'Monthly attendance': 'حضور الشهر',
    'Only records inside the current month are counted here.':
        'يتم احتساب سجلات الشهر الحالي فقط هنا.',
    'No attendance records in this month yet.':
        'لا توجد سجلات حضور في هذا الشهر حتى الآن.',
    'Payment follow-up': 'متابعة الدفع',
    'No open cash invoices.': 'لا توجد فواتير كاش مفتوحة.',
    'Academy alerts sent to your guardian account.':
        'تنبيهات الأكاديمية المرسلة لحساب ولي الأمر.',
    'No next lesson available.': 'لا يوجد درس تالي متاح.',
    'Guardian Insights': 'ملاحظات ولي الأمر',
    'Important follow-up points from real student data.':
        'نقاط متابعة مهمة من بيانات الطالب الحقيقية.',
    'Attendance needs follow-up': 'الحضور يحتاج متابعة',
    'Learning progress is low': 'تقدم المذاكرة منخفض',
    'Overdue payment': 'دفعة متأخرة',
    'Cash payment due': 'مبلغ كاش مستحق',
    'Unread academy alerts': 'تنبيهات أكاديمية غير مقروءة',
    'No urgent follow-up': 'لا توجد متابعة عاجلة',
    'Progress, attendance, and payments have no critical alerts.':
        'لا توجد تنبيهات حرجة في التقدم أو الحضور أو المدفوعات.',
    'Improve attendance consistency': 'تحسين انتظام الحضور',
    'Add a fixed study block': 'إضافة وقت مذاكرة ثابت',
    'Settle cash balance': 'سداد الرصيد النقدي',
    'Monthly status is stable': 'حالة الشهر مستقرة',
    'No urgent attendance, progress, or payment action is needed.':
        'لا توجد إجراءات عاجلة مطلوبة للحضور أو التقدم أو الدفع.',
    'Open tasks': 'المهام المفتوحة',
    'Students visible': 'الطلاب المتاحون',
    'Groups visible': 'المجموعات المتاحة',
    'Recent enrollments': 'الإضافات الحديثة',
    'Priority queue': 'قائمة الأولوية',
    'Pending items that usually need staff follow-up.':
        'العناصر المعلقة التي تحتاج عادة متابعة الموظفين.',
    'No priority items right now.': 'لا توجد عناصر أولوية حاليا.',
    'No pending leave requests.': 'لا توجد طلبات غياب معلقة.',
    'No invoices need follow-up.': 'لا توجد فواتير تحتاج متابعة.',
    'Attendance exceptions': 'استثناءات الحضور',
    'No recent absent or late records.': 'لا توجد سجلات غياب أو تأخير حديثة.',
    'No recent enrollments visible.': 'لا توجد إضافات حديثة متاحة.',
    'Unified operations queue': 'قائمة العمليات الموحدة',
    'Run the latest operations migration to enable this queue.':
        'نفذ آخر migration للعمليات لتفعيل هذه القائمة.',
    'Students Directory': 'دليل الطلاب',
    'Groups Roster': 'قائمة المجموعات',
    'Search groups': 'بحث المجموعات',
    'Some operations could not be loaded.': 'تعذر تحميل بعض العمليات.',
    'More issues are available in logs.': 'توجد مشاكل أخرى في السجلات.',
    'Unread notifications': 'الإشعارات غير المقروءة',
    'No access': 'لا توجد صلاحية',
    'Phone': 'الهاتف',
    'School': 'المدرسة',
    'Subject': 'المادة',
    'Close': 'إغلاق',
    'students.view permission is required.': 'صلاحية students.view مطلوبة.',
    'groups.view permission is required.': 'صلاحية groups.view مطلوبة.',
    'Search Students (Name, Code, Email)': 'بحث الطلاب (الاسم، الكود، البريد)',
    'No students found.': 'لا يوجد طلاب.',
    'Student Code': 'كود الطالب',
    'Grade': 'الصف',
    'N/A': 'غير متاح',
    'Search Parents (Name, Email, Phone)':
        'بحث أولياء الأمور (الاسم، البريد، الهاتف)',
    'No parents found.': 'لا يوجد أولياء أمور.',
    'Parent Record': 'سجل ولي أمر',
    'Occupation': 'الوظيفة',
    'No teachers found.': 'لا يوجد مدرسون.',
    'Teacher Record': 'سجل مدرس',
    'Specialization': 'التخصص',
    'General': 'عام',
    'No active groups found.': 'لا توجد مجموعات نشطة.',
    'Max Capacity': 'السعة القصوى',
    'Unlimited': 'غير محدودة',
    'No active branches found.': 'لا توجد فروع نشطة.',
    'No address provided': 'لا يوجد عنوان',
    'No active subjects found.': 'لا توجد مواد نشطة.',
    'No description': 'لا يوجد وصف',
    'No active schedules found.': 'لا توجد جداول نشطة.',
    'Day': 'اليوم',
    'Location': 'المكان',
    'Unassigned Room': 'قاعة غير محددة',
    'No questions found in Question Bank.': 'لا توجد أسئلة في بنك الأسئلة.',
    'Type': 'النوع',
    'Points': 'الدرجات',
    'Difficulty': 'الصعوبة',
    'options': 'اختيارات',
    'No assigned homework found.': 'لا توجد واجبات معينة.',
    'Due': 'الموعد النهائي',
    'Max Score': 'الدرجة النهائية',
    'No available exams found.': 'لا توجد اختبارات متاحة.',
    'Duration': 'المدة',
    'min': 'دقيقة',
    'Start': 'ابدأ',
    'No questions configured for this exam.':
        'لا توجد أسئلة معدة لهذا الاختبار.',
    'Question': 'سؤال',
    'of': 'من',
    'Autosaved': 'حفظ تلقائي',
    'Previous': 'السابق',
    'Next': 'التالي',
    'Submit Exam': 'تسليم الاختبار',
    'multiple_choice': 'اختيار من متعدد',
    'true_false': 'صح أو خطأ',
    'short_answer': 'إجابة قصيرة',
    'easy': 'سهل',
    'medium': 'متوسط',
    'hard': 'صعب',
    'No invoices issued.': 'لا توجد فواتير صادرة.',
    'Invoice': 'فاتورة',
    'Status': 'الحالة',
    'PAID': 'مدفوعة',
    'Record Cash': 'تسجيل كاش',
    'Total Due': 'إجمالي المستحق',
    'Balance': 'الرصيد',
    'Full Name': 'الاسم الكامل',
    'New Password': 'كلمة المرور الجديدة',
    'At least 6 characters': 'على الأقل 6 أحرف',
    'Name is required': 'الاسم مطلوب',
    'Save Changes': 'حفظ التغييرات',
    'Change Password': 'تغيير كلمة المرور',
    'Update': 'تحديث',
    'Account Profile': 'ملف الحساب',
    'Sign Out': 'تسجيل الخروج',
    'User': 'مستخدم',
    'Email Address': 'البريد الإلكتروني',
    'Branch Assignment': 'تعيين الفرع',
    'Provision New Student Account': 'إنشاء حساب طالب جديد',
    'Provision Student': 'إنشاء طالب',
    'Student Management': 'إدارة الطلاب',
    'Provision student accounts and review academy enrollment data.':
        'إنشاء حسابات الطلاب ومراجعة بيانات التسجيل في الأكاديمية.',
    'Search students': 'بحث الطلاب',
    'No students found': 'لا يوجد طلاب',
    'Provision students from here after branches exist.':
        'أنشئ الطلاب من هنا بعد إنشاء الفروع.',
    'Login QR': 'QR الدخول',
    'Code': 'الكود',
    'Email': 'البريد',
    'Provision New Teacher Account': 'إنشاء حساب مدرس جديد',
    'Provision Teacher': 'إنشاء مدرس',
    'Teacher Management': 'إدارة المدرسين',
    'Provision teachers and monitor their subject assignments.':
        'إنشاء حسابات المدرسين ومتابعة تكليفاتهم.',
    'Search teachers': 'بحث المدرسين',
    'No teachers found': 'لا يوجد مدرسون',
    'Provision teacher accounts after branches exist.':
        'أنشئ حسابات المدرسين بعد إنشاء الفروع.',
    'Provision New Parent Account': 'إنشاء حساب ولي أمر جديد',
    'Provision Parent': 'إنشاء ولي أمر',
    'Parent Management': 'إدارة أولياء الأمور',
    'Provision guardian accounts and link them to students.':
        'إنشاء حسابات أولياء الأمور وربطها بالطلاب.',
    'Search parents': 'بحث أولياء الأمور',
    'No parents found': 'لا يوجد أولياء أمور',
    'Provision guardian accounts, then link children.':
        'أنشئ حساب ولي الأمر ثم اربطه بالطالب.',
    'Select Child / Student': 'اختر الطالب',
    'Relationship Type': 'نوع العلاقة',
    'Father': 'الأب',
    'Mother': 'الأم',
    'Guardian': 'ولي الأمر',
    'Link Child': 'ربط طالب',
    'Provision Staff / Admin Account': 'إنشاء حساب موظف / أدمن',
    'Target Role': 'الدور المطلوب',
    'Operations Staff': 'موظف عمليات',
    'Branch Admin': 'أدمن فرع',
    'Provision Account': 'إنشاء الحساب',
    'Staff & Admin Management': 'إدارة الموظفين والأدمن',
    'Provision operations staff and branch admin accounts.':
        'إنشاء حسابات موظفي العمليات وأدمن الفروع.',
    'Provision Staff': 'إنشاء موظف',
    'No staff accounts found': 'لا توجد حسابات موظفين',
    'Provision staff or admin users from here.':
        'أنشئ حسابات الموظفين أو الأدمن من هنا.',
    'Role': 'الدور',
    'No enrolled students in this group.':
        'لا يوجد طلاب مسجلون في هذه المجموعة.',
    'Roll Call': 'تسجيل الحضور',
    'Finalize': 'إنهاء',
    'Attendance finalized.': 'تم إنهاء الحضور.',
    'Attendance finalized': 'تم إنهاء الحضور',
    'Finalization error': 'خطأ أثناء إنهاء الحضور',
    'Teacher Daily Attendance Workspace': 'مساحة حضور المدرس اليومية',
    'No assigned groups found.': 'لا توجد مجموعات مسندة.',
    'No active class sessions for this group.':
        'لا توجد حصص نشطة لهذه المجموعة.',
    'Main Hall': 'القاعة الرئيسية',
    'Date': 'التاريخ',
    'Open session board': 'فتح بورد الحصة',
    'Show rotating attendance QR': 'عرض QR الحضور المتغير',
    'FINALIZED': 'منتهية',
    'Take Attendance': 'تسجيل الحضور',
    'Finalize QR attendance?': 'إنهاء حضور QR؟',
    'Students who did not scan the QR will be marked absent and this session will be completed.':
        'الطلاب الذين لم يمسحوا QR سيتم تسجيلهم غياب وسيتم إنهاء الحصة.',
    'Finalization failed': 'فشل إنهاء الحضور',
    'Attendance QR': 'QR الحضور',
    'Students scan this QR to mark themselves present. It rotates every minute.':
        'يمسح الطلاب هذا الكود لتسجيل الحضور. يتغير كل دقيقة.',
    'Waiting for token': 'في انتظار الكود',
    'Expires in': 'ينتهي خلال',
    'Checked in': 'تم التسجيل',
    'Roster will appear here.': 'ستظهر قائمة الطلاب هنا.',
    'Manual': 'يدوي',
    'Finalize Attendance': 'إنهاء الحضور',
    'Assigned group': 'المجموعة المسندة',
    'Attendance marked successfully.': 'تم تسجيل الحضور بنجاح.',
    'Attendance was not accepted.': 'لم يتم قبول تسجيل الحضور.',
    'Attendance scan failed': 'فشل مسح الحضور',
    'Scan Attendance QR': 'مسح QR الحضور',
    'Scan the QR shown by your teacher. The code changes every minute.':
        'امسح الكود الذي يعرضه المدرس. الكود يتغير كل دقيقة.',
    'Manual token': 'كود يدوي',
    'Submit Token': 'إرسال الكود',
    'Board saved.': 'تم حفظ البورد.',
    'Session Board': 'بورد الحصة',
    'Published': 'منشور',
    'Publish': 'نشر',
    'Pen': 'قلم',
    'Eraser': 'ممحاة',
    'Clear': 'مسح',
    'No class sessions scheduled today.': 'لا توجد حصص مجدولة اليوم.',
    'Mark All Present': 'تحديد الكل حاضر',
    'Group Session': 'حصة المجموعة',
    'Student ID': 'معرف الطالب',
    'Current': 'الحالي',
    'Save Roll Call': 'حفظ الحضور',
    'Finalize Roll Call': 'إنهاء الحضور',
    'Attendance Summary': 'ملخص الحضور',
    'Rate': 'النسبة',
    'Create an active subject first.': 'أنشئ مادة نشطة أولاً.',
    'Create Semester': 'إنشاء فصل دراسي',
    'Semester Name (e.g. Fall 2026)': 'اسم الفصل الدراسي (مثال: خريف 2026)',
    'Semester Code (e.g. FALL-2026)': 'كود الفصل الدراسي (مثال: FALL-2026)',
    'Failed to create semester': 'فشل إنشاء الفصل الدراسي',
    'Create Unit in': 'إنشاء وحدة في',
    'Unit Name (e.g. Unit 1: Algorithms)':
        'اسم الوحدة (مثال: الوحدة 1: الخوارزميات)',
    'Unit Code (e.g. U1-ALG)': 'كود الوحدة (مثال: U1-ALG)',
    'Failed to create unit': 'فشل إنشاء الوحدة',
    'Create Unit': 'إنشاء وحدة',
    'Create Lesson in': 'إنشاء درس في',
    'Lesson Title': 'عنوان الدرس',
    'Lesson Type': 'نوع الدرس',
    'Video': 'فيديو',
    'PDF / Document': 'PDF / مستند',
    'Interactive Quiz': 'اختبار تفاعلي',
    'Failed to create lesson': 'فشل إنشاء الدرس',
    'Create Lesson': 'إنشاء درس',
    'Attach PDF Resource': 'إرفاق مصدر PDF',
    'Resource Title': 'عنوان المصدر',
    'Storage object path': 'مسار الملف في التخزين',
    'Attach Resource': 'إرفاق المصدر',
    'PDF resource attached!': 'تم إرفاق ملف PDF بنجاح!',
    'Upload failed': 'فشل الرفع',
    'No semesters found. Add a semester to start.':
        'لا توجد فصول دراسية. أضف فصلاً دراسياً للبدء.',
    'Units': 'الوحدات',
    'Add Unit': 'إضافة وحدة',
    'Add Lesson': 'إضافة درس',
    'Attachments': 'المرفقات',
    'Upload Private PDF Resource': 'رفع ملف PDF خاص',
    'Toggle Publish': 'تغيير حالة النشر',
    'Path': 'المسار',
    'Template copied': 'تم نسخ القالب',
    'Import type': 'نوع الاستيراد',
    'No file selected': 'لم يتم اختيار ملف',
    'valid': 'صالح',
    'done': 'تم',
    'issues': 'مشكلات',
    'Importing': 'جارٍ الاستيراد',
    'Import valid rows': 'استيراد الصفوف الصالحة',
    'Choose a CSV or Excel file to preview before importing.':
        'اختر ملف CSV أو Excel لمعاينته قبل الاستيراد.',
    'The first worksheet is imported. Keep the first row as headers matching the template.':
        'سيتم استيراد ورقة العمل الأولى. اجعل الصف الأول عناوين مطابقة للقالب.',
    'Row': 'الصف',
    'Name': 'الاسم',
    'Branch ID': 'معرّف الفرع',
    'Message': 'الرسالة',
    'Ready': 'جاهز',
    'Invalid': 'غير صالح',
    'Imported': 'تم الاستيراد',
    'Failed': 'فشل',
    'Missing full_name': 'حقل full_name مفقود',
    'Invalid email': 'البريد الإلكتروني غير صالح',
    'branch_id must be a UUID': 'يجب أن يكون branch_id من نوع UUID',
    'Session Roster': 'قائمة حضور الجلسة',
    'Failed to load roster': 'فشل تحميل قائمة الحضور',
    'Attendance recorded & finalized!': 'تم تسجيل الحضور واعتماده!',
    'Recording failed': 'فشل تسجيل الحضور',
    'Save Attendance': 'حفظ الحضور',
    'Review Leave Request': 'مراجعة طلب الإجازة',
    'Leave request rejected.': 'تم رفض طلب الإجازة.',
    'Review failed': 'فشلت المراجعة',
    'Reject': 'رفض',
    'Leave request approved!': 'تمت الموافقة على طلب الإجازة!',
    'Approve': 'موافقة',
    'Sessions & Rosters': 'الجلسات وقوائم الحضور',
    'Leave Requests': 'طلبات الإجازة',
    'No class sessions found for this group.':
        'لا توجد جلسات دراسية لهذه المجموعة.',
    'No location assigned': 'لم يتم تحديد موقع',
    'Leave Request': 'طلب إجازة',
    'Upload PDF': 'رفع PDF',
    'Choose PDF': 'اختيار PDF',
    'No PDF selected.': 'لم يتم اختيار ملف PDF.',
    'Selected': 'تم الاختيار',
    'Upload & Attach': 'رفع وإرفاق',
    'PDF uploaded and attached.': 'تم رفع ملف PDF وإرفاقه.',
    'Academic Curriculum Hierarchy': 'هيكل المنهج الأكاديمي',
    'No semesters found for your taught subjects.':
        'لا توجد فصول دراسية للمواد التي تقوم بتدريسها.',
    'Upload Resource': 'رفع مصدر',
    'Code Challenges': 'تحديات البرمجة',
    'Published challenges appear in the student code workspace.':
        'تظهر التحديات المنشورة في مساحة البرمجة الخاصة بالطالب.',
    'No challenges created for this lesson yet.':
        'لم يتم إنشاء تحديات لهذا الدرس بعد.',
    'Create Challenge': 'إنشاء تحدٍ',
    'Title': 'العنوان',
    'Description': 'الوصف',
    'XP': 'نقاط XP',
    'Add Test Case': 'إضافة حالة اختبار',
    'Test Case': 'حالة اختبار',
    'Hidden': 'مخفي',
    'Case Name': 'اسم الحالة',
    'Input stdin': 'مدخلات stdin',
    'Expected stdout': 'المخرجات المتوقعة stdout',
    'Create New Group': 'إنشاء مجموعة جديدة',
    'Group Name (e.g. Programming Level 1)':
        'اسم المجموعة (مثال: برمجة المستوى 1)',
    'Group Code (e.g. GRP-PROG1)': 'كود المجموعة (مثال: GRP-PROG1)',
    'Branch': 'الفرع',
    'Failed to create group': 'فشل إنشاء المجموعة',
    'Create Group': 'إنشاء مجموعة',
    'Enroll Student in Group': 'تسجيل طالب في المجموعة',
    'Select Student': 'اختر الطالب',
    'Group price (EGP)': 'سعر المجموعة (جنيه)',
    'Discount / exemption (EGP)': 'الخصم / الإعفاء (جنيه)',
    'Content stays locked until the cash invoice is fully paid. If final price is 0, access is activated as an exemption.':
        'يظل المحتوى مقفلاً حتى يتم سداد الفاتورة النقدية بالكامل. إذا كان السعر النهائي 0، يتم تفعيل الوصول كإعفاء.',
    'Student enrolled. Content is pending cash payment.':
        'تم تسجيل الطالب. المحتوى في انتظار السداد النقدي.',
    'Student enrolled with payment exemption.':
        'تم تسجيل الطالب مع إعفاء من الدفع.',
    'Enrollment failed': 'فشل تسجيل الطالب',
    'Assign Teacher to Group': 'تعيين مدرس للمجموعة',
    'Select Teacher': 'اختر المدرس',
    'Primary Teacher': 'المدرس الأساسي',
    'Co-Teacher': 'مدرس مساعد',
    'Teacher assigned successfully!': 'تم تعيين المدرس بنجاح!',
    'Teacher assignment failed': 'فشل تعيين المدرس',
    'Assign Teacher': 'تعيين مدرس',
    'Capacity': 'السعة',
    'Back': 'رجوع',
    'Enrolled Students': 'الطلاب المسجلون',
    'Assigned Teachers': 'المدرسون المعيّنون',
    'No enrolled students.': 'لا يوجد طلاب مسجلون.',
    'No assigned teachers.': 'لا يوجد مدرسون معيّنون.',
    'Assign': 'تعيين',
    'Create New Branch': 'إنشاء فرع جديد',
    'Branch Name (e.g. Nasr City)': 'اسم الفرع (مثال: مدينة نصر)',
    'Branch Code (e.g. NASR-01)': 'كود الفرع (مثال: NASR-01)',
    'Address': 'العنوان',
    'Phone Number': 'رقم الهاتف',
    'Failed to create branch': 'فشل إنشاء الفرع',
    'Create Branch': 'إنشاء فرع',
    'Edit Branch': 'تعديل الفرع',
    'Branch Name': 'اسم الفرع',
    'Branch Code': 'كود الفرع',
    'Branch updated successfully!': 'تم تحديث الفرع بنجاح!',
    'Failed to update branch': 'فشل تحديث الفرع',
    'Create New Subject': 'إنشاء مادة جديدة',
    'Subject Name (e.g. Programming Fundamentals)':
        'اسم المادة (مثال: أساسيات البرمجة)',
    'Subject Code (e.g. CS-101)': 'كود المادة (مثال: CS-101)',
    'Failed to create subject': 'فشل إنشاء المادة',
    'Create Subject': 'إنشاء مادة',
    'Edit Subject': 'تعديل المادة',
    'Subject Name': 'اسم المادة',
    'Subject Code': 'كود المادة',
    'Subject updated successfully!': 'تم تحديث المادة بنجاح!',
    'Failed to update subject': 'فشل تحديث المادة',
    'Create Homework for': 'إنشاء واجب لـ',
    'Homework title': 'عنوان الواجب',
    'Instructions': 'التعليمات',
    'Max score': 'الدرجة القصوى',
    'Homework published.': 'تم نشر الواجب.',
    'Creation failed': 'فشل الإنشاء',
    'Teacher Homework Workspace': 'مساحة واجبات المدرس',
    'Create Homework': 'إنشاء واجب',
    'No homework assignments published yet.': 'لم يتم نشر واجبات بعد.',
    'Create Exam for': 'إنشاء اختبار لـ',
    'Exam title': 'عنوان الاختبار',
    'Duration minutes': 'مدة الاختبار بالدقائق',
    'Pass score': 'درجة النجاح',
    'Exam published.': 'تم نشر الاختبار.',
    'Teacher Exam & Quiz Workspace': 'مساحة الاختبارات الخاصة بالمدرس',
    'Create Exam': 'إنشاء اختبار',
    'No exams published yet.': 'لم يتم نشر اختبارات بعد.',
    'Pass Score': 'درجة النجاح',
    'Manual Grading & Feedback': 'التصحيح اليدوي والملاحظات',
    'Final Score': 'الدرجة النهائية',
    'Teacher Feedback': 'ملاحظات المدرس',
    'Grade & feedback submitted to student!':
        'تم إرسال الدرجة والملاحظات للطالب!',
    'Grading failed': 'فشل التصحيح',
    'Submit Grade': 'إرسال الدرجة',
    'Submissions & Manual Grading Queue':
        'التسليمات وقائمة انتظار التصحيح اليدوي',
    'No pending submissions requiring manual grading.':
        'لا توجد تسليمات معلقة تحتاج إلى تصحيح يدوي.',
    'Learner': 'الطالب',
    'Score': 'الدرجة',
    'No assigned teaching groups found.': 'لا توجد مجموعات تدريس معيّنة.',
    'Create MCQ Question with Answer Key':
        'إنشاء سؤال اختيار من متعدد مع الإجابة الصحيحة',
    'Question Prompt (e.g. What is 2 + 2?)': 'نص السؤال (مثال: ما ناتج 2 + 2؟)',
    'Option 1': 'الخيار 1',
    'Option 2': 'الخيار 2',
    'Option 3': 'الخيار 3',
    'Option 4': 'الخيار 4',
    'Correct Option (Answer Key)': 'الخيار الصحيح (مفتاح الإجابة)',
    'Option 1 is Correct': 'الخيار 1 صحيح',
    'Option 2 is Correct': 'الخيار 2 صحيح',
    'Option 3 is Correct': 'الخيار 3 صحيح',
    'Option 4 is Correct': 'الخيار 4 صحيح',
    'Default Points': 'النقاط الافتراضية',
    'MCQ Question & Answer Key saved to Question Bank!':
        'تم حفظ سؤال الاختيار من متعدد وإجابته في بنك الأسئلة!',
    'Save MCQ Question': 'حفظ سؤال الاختيار من متعدد',
    'Teacher Question Bank': 'بنك أسئلة المدرس',
    'Add MCQ Question': 'إضافة سؤال اختيار من متعدد',
    'Teaching Group': 'مجموعة التدريس',
    'Open a group to review students and request discounts.':
        'افتح مجموعة لمراجعة الطلاب وطلب الخصومات.',
    'unpaid': 'غير مدفوع',
    'Final': 'النهائي',
    'pending request': 'طلب معلق',
    'Request discount or exemption': 'طلب خصم أو إعفاء',
    'Request adjustment for': 'طلب تعديل لـ',
    'Discount amount': 'قيمة الخصم',
    'Use': 'استخدم',
    'for full exemption.': 'للإعفاء الكامل.',
    'Enter a valid amount': 'أدخل مبلغاً صالحاً',
    'Discount cannot exceed final price':
        'لا يمكن أن يتجاوز الخصم السعر النهائي',
    'Send request': 'إرسال الطلب',
    'Adjustment request sent.': 'تم إرسال طلب التعديل.',
    'Helpdesk': 'الدعم الفني',
    'Helpdesk Ticketing': 'تذاكر الدعم الفني',
    'Manage your support tickets and requests':
        'تابع تذاكر الدعم والطلبات الخاصة بك.',
    'Manage support requests for you and your children.':
        'تابع طلبات الدعم الخاصة بك وبأبنائك.',
    'Manage your technical support requests.':
        'تابع طلبات الدعم الفني الخاصة بك.',
    'Manage user support requests and technical issues.':
        'إدارة طلبات دعم المستخدمين والمشكلات الفنية.',
    'Create Ticket': 'إنشاء تذكرة',
    'New Ticket': 'تذكرة جديدة',
    'Create Support Ticket': 'إنشاء تذكرة دعم',
    'No tickets yet': 'لا توجد تذاكر بعد',
    'Create a ticket to get help with your courses or account.':
        'أنشئ تذكرة للحصول على مساعدة بخصوص الدروس أو الحساب.',
    'No tickets found in this category.': 'لا توجد تذاكر في هذا التصنيف.',
    'Unable to load support tickets. Please try again.':
        'تعذر تحميل تذاكر الدعم. حاول مرة أخرى.',
    'Briefly describe the issue': 'اكتب وصفًا مختصرًا للمشكلة',
    'Provide details...': 'اكتب التفاصيل...',
    'Related Group/Class': 'المجموعة أو الحصة المرتبطة',
    'Submit Ticket': 'إرسال التذكرة',
    'No replies yet': 'لا توجد ردود بعد',
    'Type your reply...': 'اكتب ردك...',
    'Open': 'مفتوحة',
    'In Progress': 'قيد المتابعة',
    'Closed': 'مغلقة',
    'User ID': 'معرف المستخدم',
    'Submitted': 'تم الإرسال',
    'Activity': 'النشاط',
    'System': 'النظام',
    'Ticket logged successfully.': 'تم تسجيل التذكرة بنجاح.',
    'Reply feature is coming soon!': 'ميزة الرد ستتوفر قريبًا.',
    'low': 'منخفضة',
    'normal': 'عادية',
    'high': 'عالية',
    'urgent': 'عاجلة',
    'Low': 'منخفضة',
    'Normal': 'عادية',
    'High': 'عالية',
    'Urgent': 'عاجلة',
  };
}

class _AppLocalizationsDelegate
    extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) {
    return AppLocalizations.supportedLocales.any(
      (supported) => supported.languageCode == locale.languageCode,
    );
  }

  @override
  Future<AppLocalizations> load(Locale locale) async {
    return AppLocalizations(locale);
  }

  @override
  bool shouldReload(_AppLocalizationsDelegate old) => false;
}

extension AppLocalizationX on BuildContext {
  AppLocalizations get l10n => AppLocalizations.of(this);
  String tr(String key) => AppLocalizations.of(this).t(key);
}
